### ISSUE TITLE
Doesn't work if there is another scrollable widget

### ISSUE THREAD

**Issue by gabdsg** [Jan-pp/crazy_cool_keyboard_for_flutter#1]
If you start scrolling down inside a widget like a ListView or TextField (multi line) the onPanUpdate never gets fired.

**Comment by Jan-pp** [comment]
Yeah I forgot to mention you probably don't want to use the swipe closing when using some kind of Scrollable, for obvious reasons. There is a reason keyboards can't be swipe closed by default you know :).

I may look into it later this week to see if there is nice way to deal with this. I am open to suggestions of course.

**Comment by Jan-pp** [comment]
Ok try this:
- replace `GestureDetector` with `Listener`
- replace `onPanUpdate` with `onPointerMove`
- replace `onPanEnd` with `onPointerUp`

This should make it work, but you may want to think what the ideal user experience would be like.

**Comment by gabdsg** [comment]
@Jan-pp **it works perfectly!!!**
