### ISSUE TITLE
route pop then not worked

### ISSUE THREAD

**Issue by ytsingshao** [Jan-pp/crazy_cool_keyboard_for_flutter#2]
hi. thanks for you package. so awesome.

when use for route pop from second screen. the first screen not worked for this widget.

**Comment by Jan-pp** [comment]
Did you manage to find a fix yourself?

**Comment by ytsingshao** [comment]
@Jan-pp  no.~ i can't use  "_startAnimation" in method channel callback. in here~ can not find context.~

i must be use outside this callback ~ 

now i have two way:
1. use push new route, reinit
2. use keyboard listener if mounted at outside methodChannel

i dont think there two way is best.

hope your answer~ thanks Jan-Pp

**Comment by ytsingshao** [comment]
clean my cache~ everything is ok~

closed~

thank you and good package again.
